steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/adv-dev-dotnet/dotnet:${SHORT_SHA}', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/adv-dev-dotnet/dotnet:${SHORT_SHA}']

  # Entrypoint, timeout and environment variables
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy'
           '--image=us-central1-docker.pkg.dev/adv-dev-dotnet/dotnet:${SHORT_SHA}',
           '--region=us-central1', '--platform=managed', '--allow-unauthenticated']
  
# Save logs to GCS
artifacts:
  objects:
    location: gs://dotnet-bucket
    paths:
      - ${short_SHA}_test_logs.xml

images:
  - us-central1-docker.pkg.dev/adv-dev-dotnet/dotnet:${SHORT_SHA}

