steps:
  # Docker build and deploy
  - name: 'gcr.io/cloud-builders/docker'
    args: ['gcloud', 'builds', 'submit', '-t', 'gcr.io/adv-dev-dotnet/dotnet', '.']

  # Entrypoint, timeout and environment variables
  - name: google/cloud-sdk
    timeout: 240s
    args:
      [
        'gcloud',
        'run',
        'deploy',
        '--image',
        'gcr.io/adv-dev-dotnet/dotnet',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

# Save logs to GCS
options:
  logging: CLOUD_LOGGING_ONLY
