steps:
  # Docker build and deploy
  - name: 'Build and push image'
    args: ['gcloud', 'builds', 'submit', '-t', 'gcr.io/adv-dev-dotnet/dotnet', '.']

  # Entrypoint, timeout and environment variables
  - name: 'Deploy container'
    timeout: 240s
    args:
      [
        'gcloud',
        'run',
        'deploy',
        'dotnet-${SHORT_SHA}',
        '--image=us-central1-docker.pkg.dev/adv-dev-dotnet/dotnet',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

# Save logs to GCS
options:
  logging: CLOUD_LOGGING_ONLY
