steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/adv-dev-dotnet/dev-dotnet/dotnet', '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/adv-dev-dotnet/dev-dotnet/dotnet']

  # Entrypoint, timeout and environment variables
  - name: google/cloud-sdk
    args:
      [
        'gcloud',
        'run',
        'deploy',
        'dotnet-${SHORT_SHA}',
        '--image=us-central1-docker.pkg.dev/adv-dev-dotnet/dev-dotnet/dotnet',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

# Save logs to GCS
options:
  logging: CLOUD_LOGGING_ONLY
