name: adv-ci

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  angular-build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Restore Node Dependencies
        run: npm ci
        working-directory: ./client-app
      - name: Build
        run: npm run build
        working-directory: ./client-app
      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: dotnetbuild
          path: ./
