name: adv-ci

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  dotnet-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: dotnetbuild
          path: ./

  angular-build:
    needs: dotnet-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dotnetbuild
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Restore Node Dependencies
        run: npm ci
        working-directory: ./client-app
      - name: Build
        run: npm run build
        working-directory: ./client-app
